version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_fastapi
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  db_test:
    container_name: "db_test"
    image: postgres:16-alpine
    volumes:
      - db_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"

volumes:
  db_data:
  db_test: