version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_fastapi
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  db_data: