"""create association table

Revision ID: 0495465c5d5c
Revises: d580a3cefd52
Create Date: 2024-02-28 02:41:48.076669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0495465c5d5c'
down_revision: Union[str, None] = 'd580a3cefd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelog_project_association_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timelog_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timelog_id'], ['timelog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timelog_id', 'project_id', name='idx_unique_timelog_project')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_table('timelog_project_association_table')
    # ### end Alembic commands ###
