"""update position

Revision ID: 3702c680f5d5
Revises: af7f72b4db77
Create Date: 2024-03-03 00:23:36.577399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3702c680f5d5'
down_revision: Union[str, None] = 'af7f72b4db77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('salary', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'salary')
    # ### end Alembic commands ###
