"""delete role

Revision ID: af7f72b4db77
Revises: 2077f6cf02fd
Create Date: 2024-03-03 00:05:26.980966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7f72b4db77'
down_revision: Union[str, None] = '2077f6cf02fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_fk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_fk', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
