"""corrected db | project_fk

Revision ID: f43ab69b5146
Revises: f77ffa90bc45
Create Date: 2024-03-05 19:24:11.806169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43ab69b5146'
down_revision: Union[str, None] = 'f77ffa90bc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelog', sa.Column('project_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'timelog', 'project', ['project_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timelog', type_='foreignkey')
    op.drop_column('timelog', 'project_fk')
    # ### end Alembic commands ###
